name: Test and Generate Jacoco Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
    - name: Generate JaCoCo Badges for Module domains-common
      id: jacocoBadgeDomainsCommon
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
        jacoco-csv-file: domains-common/build/reports/jacoco/test/jacocoTestReport.csv
        coverage-badge-filename: coverage.svg
        badges-directory: .github/badges/domains-common/jacoco
    - name: Generate JaCoCo Badges for Module course-domain
      id: jacocoBadgeCourseDomain
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
        jacoco-csv-file: course-domain/build/reports/jacoco/test/jacocoTestReport.csv
        coverage-badge-filename: coverage.svg
        badges-directory: .github/badges/course-domain/jacoco
    - name: Generate JaCoCo Badges for Module student-domain
      id: jacocoBadgeStudentDomain
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
        jacoco-csv-file: student-domain/build/reports/jacoco/test/jacocoTestReport.csv
        coverage-badge-filename: coverage.svg
        badges-directory: .github/badges/student-domain/jacoco
    - name: Generate JaCoCo Badges for Module srs-app
      id: jacocoBadgeMonoRestServices
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
        jacoco-csv-file: srs-app/build/reports/jacoco/test/jacocoTestReport.csv
        coverage-badge-filename: coverage.svg
        badges-directory: .github/badges/srs-app/jacoco
    - name: Amend commit if any of the badges changed
      run: |
        if [[ `git status --porcelain` ]];
          then
            echo "changes in badge detected ${{ github.head_ref }}"
            git fetch --all
            git checkout ${{ github.head_ref }}
            git config --global user.name 'Adrian Yago'
            git config --global user.email 'ayago@users.noreply.github.com'
            git add --all
            git commit -m "[GA: test-coverage-badge]: Updated test coverage badges"
            git push
          else
            echo "No changes in badges after test run"
        fi
